### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by booox** [booox/Learn-Notes#4]
- [ ] [Git Help- GitHub](http://www.git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration)
- [ ] 声音传感器，将音乐图形化
- [ ] [Arduino and Python](http://playground.arduino.cc/Interfacing/Python)
- [ ] [Arduino and Python: Learn Serial Programming](http://makezine.com/projects/arduino-and-python-learn-serial-programming/) **When a new feed comes, the LED on**
- [ ] [Try SQL](https://www.codeschool.com/courses/try-sql)
- [ ] [Discover DevTools - CodeSchool](http://discover-devtools.codeschool.com/)
  - [ ] [tudou: DevTools Videos](http://www.tudou.com/plcover/AQjMMcXsjtg/)
